[package]
name = "rclone-automount"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_plain = "1.0.2"
tokio = { version = "1.47.0", features = ["full"] }
toml = "0.9.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
